#cloud-config
# настройка пользователей
users:
  - name: test
    groups: [sudo]
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - добавьте публичный ключ

# Настройка SSH-сервера
write_files:
  - path: /etc/ssh/sshd_config.d/01-cloudinit.conf
    content: |
      PasswordAuthentication no
      ChallengeResponseAuthentication no
      UsePAM yes
      PubkeyAuthentication yes
      AuthorizedKeysFile .ssh/authorized_keys

# Перезапуск SSH-сервера после применения настроек
runcmd:
  - systemctl restart sshd
